name: Docker Image CI
on:
  push:
    branches: [ master ]
  #workflow_dispatch:
jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy on nuget
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
          OWNER: aydinfurkan

        run: |
          dotnet pack -c Release /p:Version=0.0.${{ github.run_number }}
          dotnet nuget add source "https://nuget.pkg.github.com/$OWNER/index.json" --name github --username $OWNER --password $CR_PAT --store-password-in-clear-text
          dotnet nuget push "**/*.nupkg" --source "github"
      
